# Generated by Django 4.2.3 on 2023-08-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproperty',
            name='follow_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userproperty',
            name='followed_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userproperty',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='followed', to='users.userproperty'),
        ),
    ]
