# Generated by Django 4.2.3 on 2023-08-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userproperty_follow_num_userproperty_followed_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproperty',
            name='blog_watch_log',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_property', to='users.blogwatchlog'),
        ),
        migrations.AlterField(
            model_name='userproperty',
            name='perweb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
