# Generated by Django 4.2.3 on 2023-08-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userproperty_blog_watch_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproperty',
            name='profile_activite',
            field=models.BooleanField(default=False),
        ),
    ]
