# Generated by Django 4.2.3 on 2023-08-12 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userproperty_profile_activite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userproperty',
            old_name='profile_activite',
            new_name='profile_activate',
        ),
    ]
