# Generated by Django 4.2.3 on 2023-08-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_profile_activite_userproperty_profile_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproperty',
            name='blog_watch_log',
            field=models.ManyToManyField(blank=True, related_name='user_property', to='users.blogwatchlog'),
        ),
    ]
