# Generated by Django 4.2.3 on 2023-08-20 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userproperty_blog_watch_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproperty',
            name='blog_watch_log',
        ),
        migrations.AddField(
            model_name='blogwatchlog',
            name='user_property',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_watch_log', to='users.userproperty'),
            preserve_default=False,
        ),
    ]
