# Generated by Django 4.2.3 on 2023-08-24 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_userproperty_blog_watch_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogwatchlog',
            name='user_property',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.userproperty'),
        ),
    ]
