# Generated by Django 4.2.3 on 2023-08-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userproperty_introduce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproperty',
            name='introduce',
            field=models.CharField(default='这个人很懒，什么也没留下', max_length=16),
        ),
    ]
