# Generated by Django 4.2.3 on 2023-08-25 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_userproperty_introduce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproperty',
            name='profile_activate',
        ),
    ]
