# Generated by Django 4.2.3 on 2023-08-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_userproperty_profile_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproperty',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userproperty',
            name='sex',
            field=models.SmallIntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0),
        ),
    ]
