# Generated by Django 4.2.3 on 2023-07-30 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blogpostmidea'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='<django.db.models.fields.DateTimeField>', max_length=200)),
                ('image', models.ImageField(upload_to='images/blogpost_photo/')),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_num',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='BlogPostMidea',
        ),
        migrations.AddField(
            model_name='blogpostmedia',
            name='blogpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blogpost'),
        ),
    ]
