# Generated by Django 4.2.3 on 2023-07-30 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_rename_active_blogpostmedia_activete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostmedia',
            old_name='activete',
            new_name='activate',
        ),
    ]
