# Generated by Django 4.2.3 on 2023-07-30 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_rename_activete_blogpostmedia_activate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostmedia',
            name='name',
        ),
    ]
