# Generated by Django 4.2.3 on 2023-08-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_blogpostmedia_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image_num',
        ),
    ]
