# Generated by Django 4.2.3 on 2023-08-26 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_likeblogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='like_user',
        ),
    ]
